/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "double_v.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
double_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		double_in double_func_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case double_func:
		_xdr_argument = (xdrproc_t) xdr_double_in;
		_xdr_result = (xdrproc_t) xdr_double_out;
		local = (char *(*)(char *, struct svc_req *)) double_func_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
double_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		double_in double_func_2_arg;
		double_in double_func2_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case double_func:
		_xdr_argument = (xdrproc_t) xdr_double_in;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) double_func_2_svc;
		break;

	case double_func2:
		_xdr_argument = (xdrproc_t) xdr_double_in;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) double_func2_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
double_prog_12(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *double_func_12_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case double_func:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_double_out;
		local = (char *(*)(char *, struct svc_req *)) double_func_12_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DOUBLE_PROG, DOUBLE_VERS1);
	pmap_unset (DOUBLE_PROG, DOUBLE_VERS2);
	pmap_unset (DOUBLE_PROG, DOUBLE_VERS3);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS1, double_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS1, udp).");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS2, double_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS2, udp).");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS3, double_prog_12, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS3, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS1, double_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS1, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS2, double_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS2, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DOUBLE_PROG, DOUBLE_VERS3, double_prog_12, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DOUBLE_PROG, DOUBLE_VERS3, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
