/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DOUBLE_V_H_RPCGEN
#define _DOUBLE_V_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct double_in {
	long key;
};
typedef struct double_in double_in;

struct double_out {
	long value;
};
typedef struct double_out double_out;

#define DOUBLE_PROG 0x12345678
#define DOUBLE_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define double_func 1
extern  double_out * double_func_1(double_in *, CLIENT *);
extern  double_out * double_func_1_svc(double_in *, struct svc_req *);
extern int double_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define double_func 1
extern  double_out * double_func_1();
extern  double_out * double_func_1_svc();
extern int double_prog_1_freeresult ();
#endif /* K&R C */
#define DOUBLE_VERS2 2

#if defined(__STDC__) || defined(__cplusplus)
extern  void * double_func_2(double_in *, CLIENT *);
extern  void * double_func_2_svc(double_in *, struct svc_req *);
#define double_func2 2
extern  void * double_func2_2(double_in *, CLIENT *);
extern  void * double_func2_2_svc(double_in *, struct svc_req *);
extern int double_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  void * double_func_2();
extern  void * double_func_2_svc();
#define double_func2 2
extern  void * double_func2_2();
extern  void * double_func2_2_svc();
extern int double_prog_2_freeresult ();
#endif /* K&R C */
#define DOUBLE_VERS3 12

#if defined(__STDC__) || defined(__cplusplus)
extern  double_out * double_func_12(char **, CLIENT *);
extern  double_out * double_func_12_svc(char **, struct svc_req *);
extern int double_prog_12_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  double_out * double_func_12();
extern  double_out * double_func_12_svc();
extern int double_prog_12_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_double_in (XDR *, double_in*);
extern  bool_t xdr_double_out (XDR *, double_out*);

#else /* K&R C */
extern bool_t xdr_double_in ();
extern bool_t xdr_double_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DOUBLE_V_H_RPCGEN */
