/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "double_v.h"

double_out *
double_func_1_svc(double_in *argp, struct svc_req *rqstp)
{
	static double_out  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
double_func_2_svc(double_in *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

void *
double_func2_2_svc(double_in *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

double_out *
double_func_12_svc(char **argp, struct svc_req *rqstp)
{
	static double_out  result;

	/*
	 * insert server code here
	 */

	return &result;
}
