/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "double_v.h"
#include <iostream>

void
double_prog_1(char *host)
{
	CLIENT *clnt;
	double_out  *result_1;
	double_in  double_func_1_arg;
	
#ifndef	DEBUG
	clnt = clnt_create (host, DOUBLE_PROG, DOUBLE_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = double_func_1(&double_func_1_arg, clnt);
	if (result_1 == (double_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
double_prog_2(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	double_in  double_func_2_arg;
	void  *result_2;
	double_in  double_func2_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DOUBLE_PROG, DOUBLE_VERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = double_func_2(&double_func_2_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = double_func2_2(&double_func2_2_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
double_prog_12(char *host)
{
	CLIENT *clnt;
	double_out  *result_1;
	char * double_func_12_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DOUBLE_PROG, DOUBLE_VERS3, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = double_func_12(&double_func_12_arg, clnt);
	if (result_1 == (double_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	double_prog_1 (host);
	double_prog_2 (host);
	double_prog_12 (host);
exit (0);
}
